christmas_calendar = {
    "335": "Start the season by greeting everyone with a warm Merry Christmas.",
    "336": "Take cookies, or cupcakes to your local fire department or police department.",
    "337": "Volunteer to help decorate your local library",
    "338": "Take an extra pair of gloves or mittens to school. Give them to someone who has none",
    "339": "Make a coupon for 'One free Snow Clearing'.  Give it to a neighbour who could use the help",
    "340": "Make some cookies or cupcakes to give to your neighbours.",
    "341": "Give a hot drink to the person ringing the Salvation Army bell.",
    "342": "Make a christmas card and mail it to a friend or relative",
    "343": "Make a thank you card for your mail carrier",
    "344": "Donate food to your local food pantry",
    "345": "Send a care package to someone in the military",
    "346": "Make a gift for your teacher or aide",
    "347": "Drop off dog or cat food at an animal shelter",
    "348": "Sing Christmas Carols for your neighbours",
    "349": "Sort through your toys and donate any that you no longerplay with to charity , local church or library",
    "350": "Make a winter bird feeder",
    "351": "Make a christmas card for your school crossing guard",
    "352": "Donate a coat or hoodie to charity. Leave a happy note in the pocket",
    "353": "Smile all day",
    "354": "Call or email an elderly relative to wish them a happy christmas",
    "355": "Offer to help an elderly friend or relative put up their christmas decorations",
    "356": "Tell family members what you love about them",
    "357": "Share a book with a friend",
    "358": "Christmas Eve. Don't forget to leave cookies and milk for Santa and some carrots for the reindeers",
    "359": "Christmas Day. Have a great day opening your presents and be kind by helping to clear up and recycle all that wrapping paper",
    "360": "Deliver a meal to a neighbour",
    "361": "Give compliments to the people you meet today",
    "362": "Pick up trash in your neighborhood",
    "363": "Write Thank you notes for the people who gave you presents",
    "364": "Help take down and put away your christmas decorations",
    "365": "New Years Eve. Make a resolution for the new year",
}
